// Datos de temas y preguntas
const topics = [
  "Componentes electrónicos",
  "Arduino básico",
  "Conexiones y sensores",
  "Errores divertidos",
  "Imaginá y creá",
  "Cuidado y seguridad",
  "Proyectos locos",
];

const questions = {
  "Componentes electrónicos": [
    "¿Qué componente usás para encender una luz?",
    "¿Para qué sirve una resistencia?",
    "¿Cómo se ve un LED y qué hace?",
    "¿Qué pasa si conectás mal la polaridad de un componente?",
    "¿Cómo diferenciar una batería de una pila?",
    "¿Para qué sirve un zumbador o buzzer?",
    "¿Conocés algún componente que sirva para detectar luz o temperatura?",
  ],
  "Arduino básico": [
    "¿Qué es Arduino y para qué se usa?",
    "¿Qué parte de Arduino se conecta a la computadora?",
    '¿Qué hace la función "digitalWrite"?',
    '¿Sabés qué significa "pin"?',
    "¿Qué pasa si olvidás cargar el código en la placa?",
    "¿Qué proyecto harías con luces y sonidos?",
    "¿Qué se necesita para encender un LED desde Arduino?",
  ],
  "Conexiones y sensores": [
    "¿Cómo se conecta un sensor a Arduino?",
    "¿Qué colores tienen los cables jumper?",
    "¿Qué es un pin GND y por qué es importante?",
    "¿Cómo conectarías un sensor de movimiento?",
    "¿Qué sensores conocés que se usan en proyectos?",
    "¿Para qué sirve un potenciómetro?",
    "¿Cómo conectarías un servomotor?",
  ],
  "Errores divertidos": [
    "¿Alguna vez conectaste algo al revés? ¿Qué pasó?",
    "¿Tuviste que revisar muchas veces por qué no funcionaba?",
    "¿Qué error te dio más risa en clase o en casa?",
    "¿Copiaste un código y no funcionó? ¿Qué hiciste?",
    "¿Te olvidaste de conectar el cable USB y no sabías por qué no andaba?",
    "¿Alguna vez se te cayó un componente y desapareció?",
    "¿Te confundiste de pin y pasó algo inesperado?",
  ],
  "Imaginá y creá": [
    "¿Qué invento harías para ayudarte a despertar?",
    "¿Cómo sería un robot que cuide tus cosas?",
    "¿Qué proyecto harías con luces y botones?",
    "¿Cómo sería una casa con todo controlado por Arduino?",
    "¿Qué invento harías para jugar con tus amigos?",
    "¿Qué proyecto harías para ayudar a alguien?",
    "¿Qué harías si tuvieras sensores de todos los tipos?",
  ],
  "Cuidado y seguridad": [
    "¿Qué cosas no hay que hacer con Arduino?",
    "¿Qué pasa si conectás algo sin revisar?",
    "¿Por qué no se debe usar agua cerca de componentes?",
    "¿Qué cuidados tenés cuando trabajás con cables?",
    "¿Qué hacés antes de guardar tus componentes?",
    "¿Cómo protegés tu placa Arduino si la llevás en la mochila?",
    "¿Qué consejos darías a alguien que empieza?",
  ],
  "Proyectos locos": [
    "¿Qué proyecto harías con luces que cambien de color?",
    "¿Cómo sería un robot que baile?",
    "¿Qué harías con un sensor que detecta ruido?",
    "¿Podrías hacer una alarma con Arduino? ¿Cómo?",
    "¿Qué te gustaría controlar desde tu celular?",
    "¿Cómo harías un juego de preguntas con Arduino?",
    "¿Qué harías con un sensor de movimiento y un parlante?",
  ],
};
